name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 1'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.11'
      - name: Lint by pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.lock
      - name: Run tests
        run: |
          pytest
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.lock
      - name: Build single-file executable
        run: |
          pyinstaller --name gears --onefile tools/cli.py
          ls -lh dist
      - uses: actions/upload-artifact@v4
        with:
          path: dist/
